# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tourist',
                'verbose_name_plural': 'tourists',
            },
        ),
        migrations.CreateModel(
            name='TouristCard',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Department')),
                ('tourist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
            options={
                'verbose_name': 'tourist_card',
                'verbose_name_plural': 'tourist_cards',
            },
        ),
    ]
